### ISSUE TITLE
dylan-compiler man page

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/opendylan#100]
We need one.

I'd be inclined to take a man page from OS X and copy their structure / syntax since they're nice and clear.

**Comment by cgay** [comment]
I basically never think of using "man foo" these days. Instead I expect "foo help" to work.  Since I want to replace dylan-compiler, make-dylan-app, et al with "dylan build", "dylan new <app>", "dylan get <pkg>", etc. I'm going to close this.  Please reopen if you think otherwise.
