### ISSUE TITLE
make-dylan-app man page

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/opendylan#101]
We need one.

As with dylan-compiler, I'd be inclined to start with the framework / syntax used by an OS X man page.

**Comment by cgay** [comment]
I basically never think of using "man foo" these days. Instead I expect "foo help" to work. Since I want to replace dylan-compiler, make-dylan-app, et al with "dylan build", "dylan new ", "dylan get ", etc. I'm going to close this. Please reopen if you think otherwise.
