### ISSUE TITLE
llvm-runtime-generator: Needs to define #f / %false in the header

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/opendylan#1023]
The runtime-generator knows about ``$runtime-referenced-objects``, however, it doesn't dump them to the generated header. I need access to ``%false`` to check for the value of a ``false-or(<string>)`` variable to conditionally run some C within the run-time.

**Comment by housel** [comment]
This was originally by design, so as to not make it too easy for C support code to deal in Dylan object representations, and encourage coming up with C-friendly representations when crossing the FFI boundary. This would be easy to add, but I think it should be used sparingly.

**Comment by waywardmonkeys** [comment]
The ``false-or(<string>)`` usage that I need to work with here is the thread name and getting that set correctly.  Due to ``dylan_false``, there is a usage or two in the MPS code that will need to be addressed.

**Comment by waywardmonkeys** [comment]
This was fixed in f3c16f0590f93814c0e8e4a84f8d91916853f39e

Thanks!
