### ISSUE TITLE
LLVM: <C-signed-int> return types on 64 bit platforms

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/opendylan#1047]
If you have C-FFI definitions that have a `result res :: <C-signed-int>` on a 64 bit build, then you end up with an error while compiling from calls to `PRIMOP wrap-abstract-integer`

```
Error: Type {<llvm-integer-type> #x01D04360 i32} does not match {<llvm-integer-type> #x0406EF30 i64}
```

According to @housel:

> **housel** brucem: I guess that's expected (since `<raw-c-signed-int>` isn't the same size as `<raw-machine-word>`)
> **brucem** housel: hmm ... so is the right change to do something in the LLVM back-end or in C-FFI?
> **housel** The right thing is to add a cast operator primitive and have C-FFI generate that
> **brucem** housel: How painful would that be?
> **housel** medium painful I guess

**Comment by housel** [comment]
Fixed in PR #1302.
