### ISSUE TITLE
keyword validation at compile-time?

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/opendylan#1051]
Are keywords validated at all at compile time? Can they be?

Example code that should warn:

```
copy-sequence(digest, start: 0, stop: 16)
```

In this case, while `copy-sequence` is open, it doesn't use `#all-keys` and it doesn't support `stop:`, so shouldn't that warn at compile time?

**Comment by BarAgent** [comment]
A method call will allow a keyword if one of its next methods permit the keyword. Since `copy-sequence` is open, I am not sure the compiler can guarantee that.

**Comment by waywardmonkeys** [comment]
I always end up wishing that we could require *only* a set of keywords as valid unless the generic says `#all-keys`. But I have to think that we can probably do better here somehow ...

**Comment by BarAgent** [comment]
I suppose the idea is to allow extensibility. A new method in the generic function, on a new type, may have a good reason for a new keyword too.

**Comment by waywardmonkeys** [comment]
Okay, just dug in more ... in this case, it was a call to `copy-sequence` on `<byte-vector>`, which is using a method sealed on `<vector>`. However, the call site wasn't sure of the type due to other issues, so it couldn't perform the check. If I add a type constraint near the call site so that it can find the sealed method, then we do get a compile-time warning.

Closing this for now unless I find something else that is going wrong with this given the current (lack of) constraints in the language.
