### ISSUE TITLE
windows installer 32-bit

### ISSUE THREAD

**Issue by rupipal** [dylan-lang/opendylan#1060]
Hi,
Can somebody share a 32-bit windows installer? The one on Open Dylan website ( http://opendylan.org/downloads/opendylan/2014.1/opendylan-2014.1-win32.exe) has trojan, very surprisingly.
Rupinder

**Comment by rupipal** [comment]
It wiped out my system Path variable!

**Comment by cgay** [comment]
Not enough info.
