### ISSUE TITLE
Possible problem with LLVM bit code emission

### ISSUE THREAD

**Issue by pedro-w** [dylan-lang/opendylan#1066]
Background: compiling gives some warnings about undefined behaviour (mostly left-shifting negative values, e.g. `I(-1)`) so I enabled clang's undefined behaviour sanitiser. To my surprise the build now failed when compiling the output of the llvm-runtime-generator.
````
clang -arch x86_64 -fexceptions -c -o obj-x86_64-darwin-llvm/x86_64-darwin-runtime.o x86_64-darwin-runtime.bc
error: Invalid alignment value
1 error generated.
````
The align parameter in the bitcode is calculated by https://github.com/dylan-lang/opendylan/blob/102d13bcbc80215e1fbf7b679bf36867c9733bf6/sources/lib/llvm/llvm-bitcode.dylan#L2398 which calls https://github.com/dylan-lang/opendylan/blob/0299e1f78b10b1acd8a9a70a1332b294e568f4f1/sources/common-dylan/numerics.dylan#L13 which calls https://github.com/dylan-lang/opendylan/blob/0299e1f78b10b1acd8a9a70a1332b294e568f4f1/sources/common-dylan/machine-words/logicals.dylan#L112 which calls https://github.com/dylan-lang/opendylan/blob/0299e1f78b10b1acd8a9a70a1332b294e568f4f1/sources/lib/run-time/run-time.h#L1613 
Now, `alignment-encoding` is sometimes called with 0 (I suppose the intention is to specify 'alignment determined by the ABI') and, I can see from the debugger that this gives crazy numbers for the alignments, because (I think) __builtin_clzl(0) is itself undefined. 
This could be fixed in alignment-encoding or any of the functions I've listed above, depends whether, in Dylan, any of these operations are 'undefined' in the C sense. On the other hand, the true problem could be calling `alignment-encoding(0)` since the parameter is a `false-or(<integer>)` and I believe `alignment-encoding(#f)` is the way to request default alignment.
What do you think?

**Comment by waywardmonkeys** [comment]
@housel?

**Comment by pedro-w** [comment]
Further to this - the test for `%count-high-zeros` suggests that the correct answer for zero is to return the machine word size.
https://github.com/dylan-lang/opendylan/blob/0299e1f78b10b1acd8a9a70a1332b294e568f4f1/sources/common-dylan/tests/machine-words.dylan#L83-L98
So, my *guess* is that, in Dylan, `count-high-zeros(0)` is intended to be well defined, unlike `__builtin_clzl(0)` in C.
