### ISSUE TITLE
Reorganize / cleanup repository

### ISSUE THREAD

**Issue by cgay** [dylan-lang/opendylan#1080]
I want to reorganize the repo a little to make its structure a little simpler and remove some of the historical baggage. The main thing is that there are many general-purpose libraries spread around the directory structure. Some in sources/lib, some not.  Ultimately they should be in their own repositories, and retrieved via a package manager, but until then perhaps a top-level lib/ directory.

See https://github.com/cgay/sandbox/blob/master/opendylan-reorg.md for some ideas, none of which are set in stone.

**Comment by BarAgent** [comment]
I documented a bunch of the directories in the top-level OVERVIEW.txt file.

**Comment by cgay** [comment]
On reflection, there are going to be a lot of assumptions made about the sources/ directory. It's probably a better plan to keep that directory and do most of the re-org underneath it.

**Comment by pedro-w** [comment]
Also the run-time library build products are placed in a subdirectory of sources/lib/run-time which is unconventional these days.

**Comment by cgay** [comment]
See also #47 from 2012.

**Comment by pedro-w** [comment]
That stuff from #47 is done now, isn't it? The libraries I've looked at have their tests in the tests subdirectory.

**Comment by cgay** [comment]
Could be that most of it is done. The bug is a bit vague. This does find some leftovers though:
$ find . -name '*-test*.dylan' | grep -v /tests/

**Comment by cgay** [comment]
Marking this complete.  Although there are things remaining in less than ideal locations, the top directory is a lot better now and I don't think I need this bug as a reminder. I hope at some point to move a lot of libraries into their own packages (or maybe a standard-libraries package/repo?)
