### ISSUE TITLE
Inconsistent results from reading <sequence-stream>

### ISSUE THREAD

**Issue by pedro-w** [dylan-lang/opendylan#1109]
`read-into!` returns a different type from `read` 
``` dylan
let stm = make(<sequence-stream>, contents: "aaaa");
  format-out("read-element = %=\n", read-element(stm));
  format-out("read = %=\n", read(stm, 1));
  format-out("read-into! = %=\n", begin
                                  let t = make(<vector>, size: 1);
                                  read-into!(stm, 1, t);
                                  t
                                end);
```
results in
```
read-element = 'a'
read = "a"
read-into! = #[97]
```
I would expect `read-into!` to produce `#['a']`, a vector of `<character>`
Note that (as it is a mutable sequence) you can `read-into!` a string and this does give the expected result.

**Comment by cgay** [comment]
Looks wrong to me, too.

Have I said how great it is that you're looking at this stuff so carefully? :)
