### ISSUE TITLE
Missing comma in module "use" clause not reported

### ISSUE THREAD

**Issue by cgay** [dylan-lang/opendylan#1134]
Possibly related to https://github.com/dylan-lang/opendylan/issues/52
```
$ make-dylan-app missing-comma
```
Change the module definition to add "import: { format-out }", as follows:
```
define module missing-comma
  use common-dylan;
  use format-out
    import: { format-out };
end module missing-comma;
```
Note that I left out the comma before `import:`. Compile the project and see this warning:
```
missing-comma/missing-comma.dylan:8: Serious warning - 
Reference to undefined binding {format-out in missing-comma}.
        ----------
        format-out("Hello, world!\n");
        ----------
```
But there's no warning about the missing comma. The mistake is hard to spot.

**Comment by waywardmonkeys** [comment]
If I remember correctly, there are warnings that get dropped in library files ... There is a file in the build directories with warnings, so see if anything shows up in there?

**Comment by cgay** [comment]
Right you are:
```
//
// Conditions for {<compilation-record> "library"}:
//

Serious warning at library.dylan:10: Invalid syntax in macro-case macro call. 

library.dylan:10:   --------------
library.dylan:10:   use format-out
library.dylan:11:     import: { format-out };
library.dylan:11: --------------------------
```

Another probable duplicate: https://github.com/dylan-lang/opendylan/issues/131
I'll file a more explicit bug for this general problem and then close out the duplicates.

**Comment by cgay** [comment]
Superseded by https://github.com/dylan-lang/opendylan/issues/1135
