### ISSUE TITLE
compiled files get put under the sources/lib/run-time directory

### ISSUE THREAD

**Issue by pedro-w** [dylan-lang/opendylan#1138]
It doesn't cause an error per se, but it is not ideal so I am noting it here.
The run-time library (and the object files) for each architecture is built in a subdir of sources/lib/run-time (e.g. obj-x86_64-darwin). It would be better to keep source and built products separate.
Also (to be confirmed) I think that changing a source file that's part of the runtime doesn't always cause a top-level make to rebuild the compiler and libs.

**Comment by housel** [comment]
Are you sure? When building with a separate build directory (abs_builddir ~= abs_srcdir) then the generated runtime files are placed in $builddir/sources/lib/run-time/obj-*). Nothing in $srcdir/sources/lib/run-time gets modified.

**Comment by housel** [comment]
That's autoconf SOP, and what people have generally come to expect from source packages over the past 25 years. When you run configure, there's no obvious place to put the build directory other than in the current directory, whether it happens to coincide with the source directory or not.

**Comment by cgay** [comment]
grumble  :)

**Comment by pedro-w** [comment]
I admit I *didn't* expect that to happen, simply because everything else goes into one of the Bootstrap.? dirs. Might be worth recommending people to use a separate build directory [(here)](https://github.com/dylan-lang/opendylan/blob/master/README.rst#building)
The thing about changes to runtime not causing anything else to rebuild may be a bug though (what do you think?) I'll check it out, maybe just me mis-remembering.
