### ISSUE TITLE
XCode 10 not compatible with OD

### ISSUE THREAD

**Issue by cgay** [dylan-lang/opendylan#1145]
From https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dylan-lang/b76ZLePF--I/mWMMWjMNAQAJ ...

Hi,

Just a warning to the group the MacOS download of OpenDylan 2014 does not 
seem to work with the command line tools that come with Xcode 10. There is 
an error in the final link when compiling.

I ended up deleting Xcode 10 and re-installing the old 9.4.1 command line 
tools which seemed to fix the problem (no 32 bit in Xcode 10???).

Regards
Gareth Baker

**Comment by cgay** [comment]
Turned out to be a problem with the 2013.2 release and 2014.1 works.

**Comment by pedro-w** [comment]
Is this right though? I have a feeling I put something on github and/or IRC about this but I can't find it now.
* Xcode 10 definitely can't do 32-bit - the compiler can still create 32-bit objects, with a deprecation warning, but there are no 32-bit libs in the SDK (previous version 9.x is still downloadable and that's OK)
* I think there were some problems with 2014.1 building non-trivial 64-bit apps, can't remember the details though sorry...

**Comment by cgay** [comment]
@pedro-w reopen if you think it's still a problem. I don't have a Mac set up to work with right now.
