### ISSUE TITLE
Revive try.opendylan.org

### ISSUE THREAD

**Issue by cgay** [dylan-lang/opendylan#1154]
This was a great tool to help people get a flavor of the language.

I prefer play.opendylan.org as a name. Less negative.

I don't know much about how try.opendylan.org worked but I can think of several issues:
* It's slow to compile the first time around. Should precompile a standard set of libs.
* Should be able to do single-file imports, so getting that worked out is a prerequisite.

**Comment by cgay** [comment]
I suppose if I want to be less negative, I should say more positive.

**Comment by cgay** [comment]
https://github.com/waywardmonkeys/http-builder

**Comment by vendethiel** [comment]
Yes please. as a lurker, this seems like a great thing to have to try it out whenever.

**Comment by timClicks** [comment]
Because it's so much faster at the build phase, perhaps use mindy?

**Comment by cgay** [comment]
Now available at https://play.opendylan.org
Build times are under 2 seconds, which I think is fast enough.
I'll close this after adding selectable examples and making it a bit prettier.

**Comment by cgay** [comment]
...but I'll track those things over at https://github.com/cgay/web-playground
