### ISSUE TITLE
Examples: Core dump in 'examples/console/factorial-small'

### ISSUE THREAD

**Issue by fraya** [dylan-lang/opendylan#1156]
Version: 2014.1
Host: linux (x86-64)

In the 'factorial' example in dir `sources/examples/console/factorial`, when compiled 'factorial-small.lid' (without `big-integers` library) it generates a `core dump` when passing some parameters. If compiled with `factorial-big.lid`, it works.

Output: 

      $ _build/bin/factorial-small 1 
      $maximum-integer = 2305843009213693951
      ELEMENT outside of range: -5
      -5
      Breaking into debugger.  

Possible problem:

      format-out("$minimum-integer = %d\n", $minimum-integer);

**Comment by pedro-w** [comment]
Confirmed on opendylan-2014. However I tried on a fairly recent (October)  version of the compiler from git (linux x64 and macos) and it did not have this error.

**Comment by cgay** [comment]
Works for me.
