### ISSUE TITLE
Web: Add slack channel to website

### ISSUE THREAD

**Issue by fraya** [dylan-lang/opendylan#1157]
Most of the chats are in Slack. Add Slack channel to 'participate' page in the website.

**Comment by cgay** [comment]
Oh, I already have this but haven't pushed it!  Thanks for the reminder.

**Comment by cgay** [comment]
https://en.wikipedia.org/wiki/1157
https://en.wikipedia.org/wiki/Common_year_starting_on_Tuesday
2019 is next
