### ISSUE TITLE
Couldn't run hello world using tutorial

### ISSUE THREAD

**Issue by sjm-tl-gh** [dylan-lang/opendylan#1197]
OS: Ubuntu 18.04.2 on x86_64
Dylan Version: 2014.1

Following the instructions from:

https://opendylan.org/documentation/getting-started-cli/hello-world.html

Got to this step:

    $ _build/bin/hello-world

First, I needed to add

    $ export LD_LIBRARY_PATH=/opt/opendylan-2014.1/lib

to avoid dynamic library load error.

then after running the binary I got:

```
Library incompatibility: library "hello-world" was compiled in production mode against an older version of used library "io", and is not compatible with the newer version.  Library "hello-world" must be recompiled to use this version of library "io"
Library incompatibility: library "hello-world" was compiled in production mode against an older version of used library "io", and is not compatible with the newer version.  Library "hello-world" must be recompiled to use this version of library "io"
Breaking into debugger.
Trace/breakpoint trap (core dumped)
```

**Comment by cgay** [comment]
I can look at this tonight at home, but I do this fairly often to make play projects to test something and it works for me. My only question is whether I have something in my environment that you don't have. I don't think I set LD_LIBRARY_PATH.

**Comment by sjm-tl-gh** [comment]
Since ```/opt/opendylan-2014.1/lib``` is not a well-known Linux library directory, I would assume you have it configured somehow so ```dlopen``` can find it (```ldconfig```?)--or ```libcommon-dylan.so``` is being found somewhere else more well known.

Here's the load error:
    ./_build/bin/hello-world: error while loading shared libraries: libcommon-dylan.so: cannot open shared object file: No such file or directory

I experienced this exact issue on my dev machine a couple of months ago, then tested it today on Ubuntu 18.04.1 freshly installed on a VM image--using only the minimal tools/libs described in the tutorial: gcc, libgc-dev

Thanks for your help!

**Comment by housel** [comment]
dylan-compiler should be linking binaries so that needed shared libraries are linked using a relative path (../lib).

We plan to do a pre-release test build in the next few days so that you can test with that.

**Comment by sjm-tl-gh** [comment]
OK, I'll come back to this issue after you get the pre-release build out.  Might make more sense anyway to put the effort into the new release.  Thanks!

**Comment by sjm-tl-gh** [comment]
Based on the comment by @housel I actually got it working, once I realized the shared library ```libcommon-dylan.so``` needed wasn't the one in the ```/opt/opendylan-2014.1/lib``` directory, but one that was newly created in ```_build/lib```--which I guesss explains the library incompatibility message.  I still had to manually set ```LD_LIBRARY_PATH```--which wasn't mentioned in the tutorial.

**Comment by sjm-tl-gh** [comment]
Looks like the issue is with Ubuntu 18.04.2.  I tried running the tutorial on Ubuntu 14.04.5, and it ran the binary without the LD_LIBRARY_PATH.  Maybe caused by different versions of the linker?

gcc on 14.04.5: version 4.8.4
gcc on 18.04.2: version 7.3.0

**Comment by cgay** [comment]
Debian 9.6, gcc 6.3.0
```
$ echo x${LD_LIBRARY_PATH}x
xx
$ make-dylan-app abc
$ cd abc
$ choose-dylan 2014.1
Old: /home/cgay/dylan/opendylan-master
New: /home/cgay/dylan/opendylan-2014.1
$ dylan-compiler -build abc
Opened project abc (/home/cgay/dylan/play/abc/abc.lid)
...
Build of 'abc' completed
Linking abc
$ ldd _build/bin/abc
	linux-vdso.so.1 (0x00007ffcce5cd000)
	libabc.so => /home/cgay/dylan/play/abc/_build/bin/../lib/libabc.so (0x00007f0ed343c000)
	libcommon-dylan.so => /home/cgay/dylan/play/abc/_build/bin/../lib/libcommon-dylan.so (0x00007f0ed31c2000)
	libdylan.so => /home/cgay/dylan/play/abc/_build/bin/../lib/libdylan.so (0x00007f0ed2c05000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0ed2901000)
	libgc.so.1 => /usr/lib/x86_64-linux-gnu/libgc.so.1 (0x00007f0ed2691000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0ed2474000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0ed226c000)
	libio.so => /home/cgay/dylan/play/abc/_build/bin/../lib/libio.so (0x00007f0ed1f82000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0ed1be3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0ed3841000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0ed19df000)
$ _build/bin/abc
Hello, world!
```

**Comment by pedro-w** [comment]
I've got the same Ubuntu and gcc as you, and didn't see the problem.  What do you get if you run `ldd` on your binary? Also, have you got any opendylan-related environment variable set? (shouldn't need any)

```
$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
$ gcc -v
Using built-in specs.
```
snip
```
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 
$ echo x${LD_LIBRARY_PATH}x
xx
```

**Comment by sjm-tl-gh** [comment]
Keep in mind that this is on a VM with a minimal Ubuntu 18.04.2, gcc, and libgc-dev, and the 2014.1 Dylan tarball extracted at /opt  (although I also see the issue on my dev machine with 18.04.2):

```    
stewart@dylanvb:~/hello-world$ ldd _build/bin/hello-world
	linux-vdso.so.1 (0x00007fff29cf4000)
	libhello-world.so => /home/stewart/hello-world/_build/bin/../lib/libhello-world.so (0x00007fb636a2f000)
	libdylan.so => /home/stewart/hello-world/_build/bin/../lib/libdylan.so (0x00007fb636470000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb63607f000)
	libcommon-dylan.so => not found
	libio.so => not found
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb635ce1000)
	libgc.so.1 => /usr/lib/x86_64-linux-gnu/libgc.so.1 (0x00007fb635a6f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb635850000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb635648000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb636e34000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb635444000)
```

**Comment by sjm-tl-gh** [comment]
Here's a complete log of the issue and the workaround:

[ubuntu18042-dylan-tut-log.txt](https://github.com/dylan-lang/opendylan/files/2916001/ubuntu18042-dylan-tut-log.txt)

(By the way, is that Emacs Lisp code in build directory?)

**Comment by sjm-tl-gh** [comment]
Per a discussion on Gitter (@pedro-w) edited the

```/opt/opendylan-2014.1/share/opendylan/build-scripts/x86_64-linux-build.jam```

file and added

```LINKFLAGSDLL ?= -Wl,-z,origin -Wl,-rpath,\\$ORIGIN/ ;```

after the ```LINKFLAGSEXE`` entry.  This fixes my issue.

(see https://github.com/dylan-lang/opendylan/commit/cf511ed313f1f928f0b2684b569296e6f97e875c)

**Comment by cgay** [comment]
Same as https://github.com/dylan-lang/opendylan/issues/1064.  Should be fixed in next release.
