### ISSUE TITLE
Can't build on fedora 29

### ISSUE THREAD

**Issue by pedro-w** [dylan-lang/opendylan#1200]
I did a fresh install of Fedora 29 x86_64 with LXQt and 'Development packages' selected from the installer.

I downloaded 2014.1 and used it to build dylan from the current git master. All was OK apart from a missing perl package

```
Can't locate Time/HiRes.pm in @INC (you may need to install the Time::HiRes module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /home/peter/Projects/opendylan/admin/builds/fdmake.pl line 7.
```
The solution was straightforward :  `sudo dnf install perl-Time-HiRes`

Not sure if this can be picked up in config but am reporting it as an issue, in case anyone else encounters it.

**Comment by housel** [comment]
PR#1205 adds a check for the Time::HiRes module to the configure script, which should help identify this problem where it exists.

**Comment by pedro-w** [comment]
Confirmed that #1205 catches the missing package on a fresh Fedora 29 install. Thanks.
