### ISSUE TITLE
Fix low contrast in docs

### ISSUE THREAD

**Issue by cgay** [dylan-lang/opendylan#1222]
The left sidebar on our docs is full of extremely low contrast grey text on grey background.
Example: https://drive.google.com/open?id=1eP83oCdX_kUh2-39rIJZl_440GcjrPbB

**Comment by pedro-w** [comment]
I looked into this; IMO the easiest (non-hack) way would to rebuild the `sphinx_rtd_theme` that we use, with customization to avoid the grey-on-grey color scheme. But this seems to be impossible at the moment until https://github.com/readthedocs/sphinx_rtd_theme/pull/808 is merged. I am keeping an eye on that PR and I will have a go at rebuilding the theme when it is done.

**Comment by cgay** [comment]
Sounds great.

To be clear, low contrast is one of my (many) pet peeves but we probably have many more important doc bugs than this. :)

**Comment by pedro-w** [comment]
I agree. It seemed that trying to fix the theme build on my own would be a lot of learning work, but once they've done it, tweaking the contrast should be v. easy.

**Comment by davidfischer** [comment]
If you would like to contribute your changes back to `sphinx_rtd_theme`, that would be great too!

**Comment by pedro-w** [comment]
I have managed to get the latest sphinx_rtd_theme rebuilt and it looks more contrasty to my eyes. What do you think? 
![screenshot](https://user-images.githubusercontent.com/22172519/66645117-853a3500-ec1a-11e9-9e8d-d8daf0d2cbcc.png)
If OK, this can be a drop in replacement for what we currently have in the `sphinx-extensions` repo.

**Comment by cgay** [comment]
Much better.
