### ISSUE TITLE
Left nav overlaps main content

### ISSUE THREAD

**Issue by cgay** [dylan-lang/opendylan#1289]
The History web page at normal 0% magnification has the left nav overlapping the main text:
![overlapping](https://user-images.githubusercontent.com/491829/71196020-21a53700-225d-11ea-998e-a0d6cb7d3ae5.png)

When I use Ctrl-+ four times it seems to switch to some other mode (mobile?) and the overlapping goes away:
![non-overlapping](https://user-images.githubusercontent.com/491829/71196034-279b1800-225d-11ea-96fc-291b4934f4e9.png)

**Comment by pedro-w** [comment]
(should be on the https://github.com/dylan-lang/website project I suppose)
I see the website is using css from 'bootstrap-responsive' and the media queries change the style at the following widths
* below 480px - a 'phone-like' style
* up to 768px - left nav on top (OK)
* up to 980px - left nav on left (OK)
* above this - left nav overlaps (not OK)

I can look at this in a more detail to figure it out. Note the css file is quite old (bootstrap 2.3.1 is from 2013)

**Comment by pedro-w** [comment]
Based on modifying styles 'by hand' in the Developer tools, I think the navigation elements need to be in a div of class `row-fluid` rather than `row`. The source of this is in `source/history/index.rst`, line 3.
There may well be other instances of this, e.g. Documentation and Participate.

**Comment by cgay** [comment]
Moved to https://github.com/dylan-lang/website/issues/96
