### ISSUE TITLE
Compiler doesn't print error messages if "define library" definition is missing

### ISSUE THREAD

**Issue by AndrewGlynn** [dylan-lang/opendylan#131]
Given the following files:

test.lid:

```
library: test
files:   library
```

library.dylan:

```
module: dylan-user

define module test
  use dylan;
end module;
```

Running dylan-compiler -build test.lid displays no error messages, even though a serious warning is found. It does print the following notice:

```
Dumping conditions to undefined-library.log
There were 0 warnings, 1 serious warnings.
```

In the build output directory, undefined-library.log contains the missing error message:

```
//
// Conditions for {<compilation-record> "library"}:
//

Serious warning at library.dylan:3: 
  No define library seen for the current library - skipping definition of the test module. 

library.dylan:3: -------------------
library.dylan:3: define module test 
library.dylan:4:   use dylan;
library.dylan:5: end module;
library.dylan:5: ----------
```

Note that the entire "define library" definition need not be missing to cause this issue. It suffices to leave out (or misspell) "define" or "library" in an otherwise correct "define library" definition.

**Comment by cgay** [comment]
Superseded by https://github.com/dylan-lang/opendylan/issues/1135
