### ISSUE TITLE
Crash when calling %call-c-function

### ISSUE THREAD

**Issue by Outcue** [dylan-lang/opendylan#1347]
Running the unit tests for [objc-dylan](https://github.com/dylan-foundry/objc-dylan) using dylan-compiler Version 2020.1, the following crash occurs:

```
* thread #1, name = 'Main thread', queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00000001006f6690 libobjc-dylan.dylib`import-function-for-<objc/instance> [inlined] objc/raw-instance-class at instance.dylan:45:8
   42  	 => (raw-objc-class :: <machine-word>)
   43  	  primitive-wrap-machine-word
   44  	    (primitive-cast-pointer-as-raw
-> 45  	      (%call-c-function ("object_getClass")
   46  	            (objc-instance :: <raw-c-pointer>)
   47  	         => (objc-class :: <raw-c-pointer>)
   48  	          (primitive-unwrap-machine-word(objc-instance))
```

Before diving in, I thought I would see if this is an obvious issue, as the obj-dylan code has gone stale.

**Comment by housel** [comment]
The LLVM back-end is picky about mixing pointer and unsigned integer types. Some places in the objective-c library were fixed in 2016, but there are a couple more fixes needed. I'll finish making them and submit a PR.

**Comment by housel** [comment]
Should be fixed in objc-dylan now.
