### ISSUE TITLE
segfault with locator-name

### ISSUE THREAD

**Issue by pedro-w** [dylan-lang/opendylan#1372]
On 2020.1, I was using `list-locator` to get a directory content. If I try to use `locator-name` on the elements, those which are files (rather than subdirectories) will cause a segmentation fault, which doesn't seem to have a sensible backtrace.

I see that `list-locator` uses `do-directory` internally, and its callback converts to a `<file-system-file-locator>` when the entry is a file.
https://github.com/dylan-lang/opendylan/blob/dd81048dfd2d00c6bbc3ba359934ee24779d0789/sources/system/file-system/file-system.dylan#L496-L515

Using this info, I can reproduce the crash with this reduced program.
```dylan
Module: scratch
Synopsis: 
Author: 
Copyright: 

/*
 Use libraries: system, common-dylan, io
 Use modules: file-system, locators, common-dylan, format-out
*/
define function main
    (name :: <string>, arguments :: <vector>)
  let d = make(<file-system-file-locator>, directory: as(<directory-locator>, "/tmp/"), name:"me.txt");
  format-out("%s\n", d.locator-name);
  exit-application(0);
end function main;

main(application-name(), application-arguments());
```

I see the same on MacOS (Mojave) and Debian 10.

Here I am a bit confused. I couldn't find an  implementation of `locator-name` for `<file-system-file-locator>` (there is one for `<posix-locator>` which has `<file-system-file-locator>` as a superclass)
So I can't figure out why does `do-directory` return instances of `<file-system-file-locator>` and not something more concrete, and why do I get a 'hard' crash and not a no-method-found traceback?

**Comment by pedro-w** [comment]
The explanation is:
* `<file-system-file-locator>` doesn't have specialization for `locator-name` which triggers a no-applicable-method-error, which is displayed using the format "No applicable method, applying %= to %=."
* `<locator>`s are formatted by calling `locator-as-string` but `<file-system-file-locator>` doesn't have a specialization for that either, so there is recursion until the stack runs out (and nothing is printed)

**Comment by cgay** [comment]
https://photos.app.goo.gl/UtUVXznia7C51HPB7

**Comment by pedro-w** [comment]
A potential fix for the immediate problem is to change `list-locator`, specifically replace the 
```
#"file", #"link" =>
    make(<file-system-file-locator>,
       directory: locator,
       name:      name);
```
with
```
#"file", #"link" =>
    merge-locators(as(<file-locator>, name), locator);
```
Possibly there was an intention to specialize `make` to create a more specific instance of `<file-system-file-locator>` based on the class of `directory:`, but this didn't happen?
A wider point is that `<file-system-file-locator>` and some of its brethren (see the class hierarchy in the comment above!) are not defined as abstract classes (AFAICT) but they are 'de facto' because they don't have specializations for all the GFs in `<locator>`, meaning you could create a instance of them and cause some other code to crash (my code, in this case, when I call `locator-name`)

The second thing is error handling when already within an error handler. Is there any way to stop this recursive behaviour? Even it just raised an exception then and there, the back-trace would be reasonable. 
More directly, maybe when printing the message for a no-applicable-method-error we could print out just the classes of the arguments, instead of their %= representation, which could be anything and potentially very long. I think this would actually be more useful, and avoid the crash-within-a-crash, because all instances have `object-class` defined.
