### ISSUE TITLE
Doc: Code block in verbatim

### ISSUE THREAD

**Issue by fraya** [dylan-lang/opendylan#1545]
The block is not rendered correctly in documentation ([https://opendylan.org/library-reference/io/print.html#io:pprint:\*print-miser-width\*](https://opendylan.org/library-reference/io/print.html#io:pprint:*print-miser-width*)) and shows its verbatim content.

https://github.com/dylan-lang/opendylan/blob/34b45aa96d39ccaa16f3fb0f5f764a0045745335/documentation/library-reference/source/io/print.rst?plain=1#L522

**Comment by cgay** [comment]
It looks like this is because of the `::` ending the previous paragraph and the extra indentation for the code block.  `::` means to put any following indented section in verbatim.
