### ISSUE TITLE
HARP backend using Boehm GC

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/opendylan#413]
Experimentally, we'd like to have the HARP backend using the Boehm GC as a config option.

I recently landed a branch that did a lot of work in this direction, but it isn't tested using Boehm and doesn't have full feature parity.

**Comment by cgay** [comment]
Bruce, I think more recently you had a branch to delete HARP altogether. Is that correct?  (In which case I'll close this bug.)
