### ISSUE TITLE
Typo in export from module not reported

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/opendylan#52]
If I forget a `,` in my exports statement in a module definition like this:

``` dylan
  export <uv-err> uv-last-error, uv-strerror,
    uv-err-name;
```

That doesn't seem to report any error about the missing `,`, but it does go on to say that `uv-last-error`, `uv-strerror` and so on are not exported or referenced.

**Comment by cgay** [comment]
As Bruce pointed out in https://github.com/dylan-lang/opendylan/issues/1134, perhaps the warning went to the .log file in _build/build/

**Comment by cgay** [comment]
Yes, they're in the log file but do not get reported normally.
```
//
// Conditions for {<compilation-record> "library"}:
//

Serious warning at library.dylan:13: Invalid syntax for names in macro-case macro call. 

library.dylan:13:          -------
library.dylan:13:   export foo bar;
library.dylan:13:          -------
```

**Comment by cgay** [comment]
Superseded by https://github.com/dylan-lang/opendylan/issues/1135
