### ISSUE TITLE
Documentation formatting and linkage issues in the streams module library reference.

### ISSUE THREAD

**Issue by enlight** [dylan-lang/opendylan#608]
The make file-stream-class method documentation is not formatted correctly:
http://opendylan.org/documentation/library-reference/io/streams.html#file-streams

`<file-stream>` and `<console-stream>` are not linked properly:
http://opendylan.org/documentation/library-reference/io/streams.html#closing-streams

`<stream>` not linked properly:
http://opendylan.org/documentation/library-reference/io/streams.html#locking-streams

`<position-type>` not linked properly:
http://opendylan.org/documentation/library-reference/io/streams.html#positionable-stream-protocol
Also should probably add a one-liner to describe the list of methods.

Redundant description of `integer-class` parameter in the Discussion:
http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:as([integer],[stream-position])

Superclass <vector> not linked:
http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:[buffer]

Formatting inconsistent with the surrounding text:
http://opendylan.org/documentation/library-reference/io/streams.html#id4
http://opendylan.org/documentation/library-reference/io/streams.html#id5

No link to `make(<byte-string-stream-class>)`:
http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:[byte-string-stream]

Superclass `<vector>` not linked:
http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:[byte-vector]

Superclass `<error>` not linked:
http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:[end-of-stream-error]
http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:[file-error]

`<locator>` not linked...
Init-Keywords: http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:[file-stream]
Discussion: http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:make([file-stream])

Inconsistent formatting:
http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:[positionable-stream]

Superclass `<object>` not linked:
http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:[stream]

Superclass `<object>` and `<position-type>` not linked:
http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:stream-position

`<position-type>` not linked:
http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:stream-position-setter

`<stream-position-error>` not linked in Discussion:
http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:stream-position-setter

Inconsistent formatting:
http://opendylan.org/documentation/library-reference/io/streams.html#io:streams:type-for-sequence-stream

**Comment by cgay** [comment]
From the commit message:
"Fixed more incorrect links/references. Couldn't find some references (like `<stream-position-error>` and locator library), and didn't see what was meant by inconsistent formatting."

Let's assume that's all that remains to do for this bug.

**Comment by cgay** [comment]
This section received significant love from @fraya so let's call this done and report new bugs where necessary.

* 1dba458daf9f683b65bcea16ec4147c40bde7261
* 6e74b109953619b7e27d4fe4d62256b3e2f46363
* e8afab37fd67c305e99481bc2a4735c0299497e5
