### ISSUE TITLE
missing navigation links in hacker's guide (dependencies in sphinx?)

### ISSUE THREAD

**Issue by hannesm** [dylan-lang/opendylan#72]
can't navigate from http://opendylan.org/documentation/hacker-guide/runtime.html to Jam-based build system (build-system.html) since there's no link in the table of contents on the right.

Also, I can't navigate to index.html (the toc) from any subpage, since there are only links to copyright, and sections.

**Comment by cgay** [comment]
Both of these appear to have been fixed.  Can navigate to index.html by clicking on "Open Dylan Hacker Guide" in top left.
