### ISSUE TITLE
No warning shown when a source-record's module name doesn't match an actual module

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/opendylan#859]
If you have a source file where the `Module:` line is not spelled correctly, you don't see a visible error from running `dylan-compiler`, instead you have to look at the condition log file, where you'll see:

```
Serious warning:
  Module xxxxxx of source record {<compilation-record> "xxxxxxxx"}
  is not defined at this point, ignoring the source record.
```

**Comment by cgay** [comment]
Seems like an easy beginner mistake, so adding the Usability label.

**Comment by cgay** [comment]
This is a duplicate of #679.
