### ISSUE TITLE
2015.2: Remove find-value from common-extensions

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/opendylan#949]
`find-value` is marked as not being needed and in 2015.1, I have removed all usages of it. It should be safe to remove the function itself from `common-extensions` in a subsequent release.

**Comment by waywardmonkeys** [comment]
I'm not sure if this is safe for bootstrapping to have removed it without the release where it is present ... would have to try bootstrapping from 2014.1 to master to see.

**Comment by cgay** [comment]
This appears to have been done already.
