### ISSUE TITLE
Intro to Dylan: DRM links

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/opendylan#97]
This should have proper links to the DRM using the :drm: role.

**Comment by fraya** [comment]
Must every ocurrence of drmindex be linked or just the first ocurrence? 
For instance, every `let` must be linked or just the first ocurrence.

**Comment by cgay** [comment]
My opinion...  use ```:drm:`let` ``` everywhere except the examples.

**Comment by cgay** [comment]
(Not really related, but I'd love to see the Pascal references replaced with something more modern.)

**Comment by fraya** [comment]
There are `:term:`s to construct a glossary but the definition is absent. Should they link to DRM or we should make a definition? Probably it's a different issue.
