### ISSUE TITLE
Missing dylan_dump_callstack() for NetBSD

### ISSUE THREAD

**Issue by krytarowski** [dylan-lang/opendylan#986]
Can we go for something like this in stack-walker.c:

```
        void *array[10];
        size_t i, size = backtrace (array, 10);
        char **strings = (char **)(size_t)backtrace_symbols (array, size);
        printf ("Backtrace %zd stack frames.\n", size);
        for (i = 0; i < size; i++)
                printf ("%s\n", strings[i]);
        free (strings);
```

This will be portable to Linux, Apple, FreeBSD, NetBSD.... example: https://github.com/radare/radare2/blob/master/libr/util/sys.c

**Comment by housel** [comment]
The run-time code now uses libunwind, which is available on NetBSD in the lang/libunwind package.

**Comment by krytarowski** [comment]
Just making sure, do we need (non)gnu libunwind? lang/libunwind is LLVM one.

**Comment by housel** [comment]
Both use the same API; the backtrace functionality has been tested on macOS with the LLVM libunwind, and on Linux and FreeBSD with the (non)GNU one.

**Comment by krytarowski** [comment]
I see so problem solved.
