### ISSUE TITLE
getting-started-cli documentation need to be updated

### ISSUE THREAD

**Issue by dram** [dylan-lang/opendylan#999]
Some contents of "Getting Started with the Open Dylan Command Line Tools" are outdated.

When using Open Dylan 2014.1, three files plus one directory `registry/` are created. "Hello World" section do not mention that new directory.

Because of the addition of this new `registry/` directory for each project, "Using Source Registries" also need to be updated.

Btw, I think source registries need some more explanation. I once put all `.lid` files into one single regiestry file. :)

**Comment by cgay** [comment]
For user projects (as opposed to Open Dylan itself) I hope to replace registries with workspaces soon.  Leaving this bug open because the docs will still need to be updated, but in a different way.

**Comment by cgay** [comment]
I think this was addressed by https://github.com/dylan-lang/opendylan/commit/f6122ef08c31e1bd7a0f563d040362790aa76466.
